### ISSUE TITLE
LOTS AND LOTS OF BUGS FIRE!!!!!!!!

### ISSUE THREAD

**Issue by FrostTO** [firelad97/pandato#17]
Tthe drop rates+teleports arent working from what Ive seen, also, the items that were once expired and unusable went back to being normal, my dragon can now equip those zorra items, but my bunny reequiped the expired items that were in my inventory automatically once I logged in, and now I have the error of failed to install item, and I also cant take it off, same case for Kumikun. Also, Kumikun got a job change from Louis Buitton, I suggested it since it unequips everything once you change your Job look, once she did it, they unequipped but only the graphics of the items, while the items were still on her character and also on the equipment tab, and when she equipped another piece of equipment, everything showed up on her character, as well as to me, not just her client. So apparently, I have a TM issue its at 258%? While Rinkai has 400%, and Tinnky had 300% issue, not sure why. Also Upon completion of the Crazy Drilling Skill, you dont receive Detection Scrolls. In Mermaid Place, Aqu is supposed to drop the map fragment 1 for a quest item but instead Alec is the one who drops it.

**Comment by Tinnky** [comment]
I think for the TM issue, just keep accepting wuests that gives TM exp. Eventually you would level up xD. But, I'm not sure if my TM levels after reaching 300%..
